### PR TITLE
Avoid `dash--get-expand-function` create non-existing symbol.

### PR DESCRIPTION
**Pull request by cireu**

### CODE REVIEW

**Comment by Fuco1** [comment]
If this returns nil won't it break the code?  Or is that the point, to let the user know something is not right?

In that case we should probably also add a test for this behaviour so we keep it in the future.

**Comment by cireu** [comment]
Still need some research on corner case, currently have no idea on how to test it.

**Comment by basil-conto** [comment]
> If this returns nil won't it break the code?

No, because all current uses of `dash--get-expand-function` expect it to return a symbol satisfying `functionp`.

> Or is that the point, to let the user know something is not right?

This code does not seem to have been designed with that in mind.

> In that case we should probably also add a test for this behaviour so we keep it in the future.

This is part of the extensible destructuring logic added in #277, which is already being tested to an extent.  I think the general logic needs to be refactored a little before it can be more deeply and effectively tested.

**Comment by cireu** [comment]
BTW, can we use `pcase` in dash.el to reduce boilderplates in `dash--match`?

**Comment by Fuco1** [comment]
@cireu No pcase please.

@basil-conto Yea, I think I wasn't clear in my response.  I don't understand the purpose of this PR:

- what does it solve
- how does it break or not break existing code

**Comment by basil-conto** [comment]
> what does it solve

It avoids interning arbitrary and unused symbols, i.e. it keeps the environment cleaner.

> how does it break or not break existing code

It should have no effect on existing code.

This PR gets a +1 from me, but I would prefer if the commit message were clearer @cireu, e.g. `Avoid interning unused symbols in destructuring`. More generally, widespread Git convention is to limit the first line of the message to 50 characters and leave any further details for the body of the message.

**Comment by basil-conto** [comment]
Cc: @yyoncho

**Comment by cireu** [comment]
@basil-conto  Check this, changes was mentioned in commit message body.

**Comment by basil-conto** [comment]
@cireu 

> Check this, changes was mentioned in commit message body.

LGTM, thanks!

**Comment by Fuco1** [comment]
> No, because all current uses of dash--get-expand-function expect it to return a symbol satisfying functionp.

I didn't get this at first, but now I understand what you ment.

LGTM as well, if nobody has anything to add I'll merge this later today/tonight.

**Comment by cireu** [comment]
Are you ready for this PR? @Fuco1

**Comment by Fuco1** [comment]
Thanks for reminding me @cireu and sorry for the wait!

**Pull request merged**
