### PR TITLE
Use github actions instead of travis

### PR DESCRIPTION
**Pull request by conao3**
Hi! Your travis CI with something wrong Emacs-26.
I suggest switch GitHub Actions using purcell's [setup-emacs](https://github.com/purcell/setup-emacs) from TravisCI.

I have checked the workflow works well in my fork ([log](https://github.com/conao3/dash.el/commit/d38088ffdcf48696670ec11d113451b50c5089d7/checks?check_suite_id=338889566))

### CODE REVIEW

**Comment by Fuco1** [comment]
Can we keep travis also for a while to see if things work?  We can have both set up.

**Comment by conao3** [comment]
OK! Revert travis configure files.

**Comment by Fuco1** [comment]
Very cool, thanks!  I think I'll try this also on my other projects.

**Comment by Fuco1** [comment]
I looked at the actions now after the merge and it is really fast! And all of them pass, whereas travis has some issues.  I really like this, thanks for putting in the work! <3

**Comment by conao3** [comment]
OK! thanks!

**Comment by basil-conto** [comment]
@conao3 This PR is a very welcome change, thanks! Especially since EVM is failing horribly on Travis CI at the moment. ;)

I'm sorry this wasn't checked at the time, but since Dash is a FSF-copyrighted package, all nontrivial contributions (over ~15 lines) need their copyright assigned to the FSF. Do you already have such a CA on file? If not, would you be willing to submit one? In case you're unfamiliar with this, you can find more info at [`(info "(emacs) Copyright Assignment")`](https://www.gnu.org/software/emacs/manual/html_node/emacs/Copyright-Assignment.html). The process involves filling out the form at https://github.com/coreutils/gnulib/blob/master/doc/Copyright/request-assign.future and emailing it to assign@gnu.org, who will guide you from there. TIA!

**Comment by conao3** [comment]
Your welcome, I've signed FSF paper, thanks!

**Comment by basil-conto** [comment]
Ah yes, I should have checked the Emacs sources first for your `plist-get` contribution before asking! Thanks :)

**Pull request merged**
