### PR TITLE
dash.el (->, ->>): Indent with 1 distinguished arg.

### PR DESCRIPTION
**Pull request by kiennq**
Per discussion in https://github.com/magnars/dash.el/commit/92562909a763d766fd81b817418c2e05d35d50e0

### CODE REVIEW

**Comment by basil-conto** [comment]
Thanks!

**Comment by yyoncho** [comment]
FWIW this indentation change makes the indentation of -> and ->> different from the indentation they have in clojure which IMHO introduces redundant cognitive load.

(cc @ericdallo)

**Comment by ericdallo** [comment]
Yes, I though this was an issue with my emacs config, but I just realized is because of this change, I totally agree that the indentation should be like clojure

**Comment by basil-conto** [comment]
I don't feel too strongly about this, but IMO it makes more sense to follow Elisp conventions and idioms when writing Elisp (this applies to any language/environment, not just Elisp).  For example, Elisp indents `if` differently to some other Lisps.

@magnars @Fuco1 Do you favour reverting to Clojure indentation?

Thanks.

**Comment by magnars** [comment]
Since I code clojure all day, I personally prefer the Clojure indentation.
That doesn't mean it's necessarily right for this package, tho. However,
since there is now `thread-first` and `thread-last` macros in `subr-x.el`,
maybe our threading macros can have a Clojure flavor?

**Comment by yyoncho** [comment]
> I don't like the idea of imposing another language's style on users of Dash who are writing Elisp

The threading macros themselves are imposing another language style into elisp. And not only these macros - the whole package is breaking much more important elisp conventions(like package prefix and functions ending with `?`) in favor of being practical and convenient.

**Comment by basil-conto** [comment]
> The threading macros themselves are imposing another language style into elisp.

Sorry, I don't follow this logic - macros don't constitute a programming/editing language/environment.  We're talking about the syntax of Elisp, not the semantics of Elisp definitions.

> And not only these macros - the whole package is breaking much more important elisp conventions(like package prefix and functions ending with ?)

See #213 and similar discussions re: `?` vs `-p`.

> in favor of being practical and convenient.

I don't see how Elisp-style indentation is less practical or convenient when Emacs does it for you.  Besides, the Elisp-style indentation is less indented, so in my book that's actually more "practical and convenient".

**Comment by yyoncho** [comment]
It is less practical for multiple reasons. 

* It makes code less readable since `->` and `->>` are harder to distinguish. It makes a huge difference when your organization is using `->` or `->>` 250+ times. 
* As I already mentioned it introduces redundant cognitive load - all lisps having these arrows use this formatting. There are zero benefits from following that convention - if someone knows about it - most likely they won't use `dash` at all. 
* Even your "practical and convenient" point about less indentation is not in your favour... This is before:
```
(->> 
 5 
 (+ 20)
 (/ 25)
 -
 (+ 40))
```

**Comment by basil-conto** [comment]
> It is less practical for multiple reasons.

I said "in my book" because what counts as practical, readable, cognitively cumbersome, etc. is clearly a personal and subjective issue.

Whether undistinguished macro arguments are indented according to Clojure or Elisp conventions is less subjective, but still a stylistic choice. BTW, this being Emacs, the indentation can of course be customised per-user, per-project, etc.

I've already given my context for why I personally follow each language's conventions when writing in that language, but the decision isn't mine to make anyway.

> Even your "practical and convenient" point about less indentation is not in your favour... This is before:

According to my book, that indentation is wrong, so any argument following from that is moot ;).

**Comment by yyoncho** [comment]
I personally follow common sense and the solutions that will be most useful for the actual users. I also try to avoid inflicting pain and redundant work for stuff that I don't feel strongly about.

**Comment by basil-conto** [comment]
@magnars Your comments sounded like they were in favour of following Clojure indentation project-wide. Let me know if this is indeed the case and I'll make the necessary changes.

**Comment by magnars** [comment]
I am not involved enough to impose my will in that way. I can certainly see the value of sticking to the Emacs lisp conventions as well. In the end dash is a collection of tools for use with Elisp, so let's go for that.

**Comment by basil-conto** [comment]
> I am not involved enough to impose my will in that way.

I really respect that, but as the package's author and with feet in both the Elisp and Clojure pools, your will carries unique weight :).  But I also understand that bikesheds aren't the best hill to die on ;).

> In the end dash is a collection of tools for use with Elisp, so let's go for that.

Agreed.

**Comment by basil-conto** [comment]
We already have `dash-fontify-mode` for font-locking some Dash-isms in Elisp buffers.

Would it make sense to add something like a `dash-clojure-indent-mode` for picking between more Elisp-like and Clojure-like indentation? (Or conversely a `dash-elisp-indent-mode`, if Clojure-like indentation becomes the default in this scenario.)

This would allow projects to specify e.g.

```el
((emacs-lisp-mode (mode . dash-clojure-indent)))
```

or

```el
((emacs-lisp-mode (mode . dash-elisp-indent)))
```
in their `dir-locals-file` for easily picking one over the other.

**Comment by magnars** [comment]
That sounds pretty good to me! With elisp being the default, then.

**Comment by alphapapa** [comment]
IMHO "we" (not being a maintainer myself) should avoid unnecessary indentation changes; or, at least, space them out years apart.  I just had a spate of dash-related indentation changes in one of my projects, and that pattern will repeat for most of my others the next time I work on them.  Not only is it annoying to have to examine the diffs and commit these indentation changes manually, but they cause new linting warnings on CI until I update the package; and these warnings were not caused by any changes in my packages, they just start happening when dash is updated on MELPA.  Dash is supposed to save Elisp developers work, not create more for them.  ;)

**Comment by basil-conto** [comment]
Sorry, I thought of the indentation changes as fixes/cleanups, but I can't in good conscience controversially force them on so many Elisp authors any more. Backward compatibility wins again!

@magnars I'm guessing you don't have a problem with reconsidering this decision.  If so, for the upcoming 2.19.0 release in #382 I'll try to revert any breaking indentation changes, and add Elisp-style indentation as an opt-in feature if I have time.

Sorry again for the hassle and thanks for bearing with my stubbornness.

**Comment by magnars** [comment]
That's a good point. Let's keep it as-is, then.

**Comment by alphapapa** [comment]
@basil-conto Thank *you* for being so considerate of downstream users!  :)  Not all Elisp packages are developed with such care, and pleas like mine often fall on deaf ears elsewhere.

**Comment by basil-conto** [comment]
Ugh, the status quo (even before this PR) is a bit all over the place in terms of indentation style, see e.g. `-doto`, `--doto`, #319, #321, etc.

So my conclusion is basically to revert this PR that I'm partially responsible for and call it a day ;).

**Comment by basil-conto** [comment]
> So my conclusion is basically to revert this PR that I'm partially responsible for and call it a day ;).

I've now done so in commit 3bd52a45aa81a3aab0d02ece800042415669399a.  Please let me know if any outstanding issues remain.

**Pull request merged**
