### PR TITLE
Errant paren removed from -let documentation.

### PR DESCRIPTION
**Pull request by phillord**

### CODE REVIEW

**Comment by Fuco1** [comment]
Hm, was anything wrong with this patch?  Probably we just forget about it :O

**Comment by phillord** [comment]
Ah, oh, I had no idea that there was still an open PR attached to it. I'd assumed that it had gone in (or been bounced) or something ages ago. And I was cleaning up my repo because I had tons of branches around.

GIt is really terribly complicated!

AFAICT, the PR is still relevant, so I have restored the branch.

**Comment by Fuco1** [comment]
Thanks :) Sorry for the mess.

**Comment by phillord** [comment]
No worries! It was just an extra paren in the documentation:-)

**Comment by Fuco1** [comment]
Still, you made the effort and all.  I usually try to at least ack that, but somehow this PR slipped through my nets P

**Pull request merged**
