### PR TITLE
Add -common-suffix

### PR DESCRIPTION
**Pull request by basil-conto**
Update `-common-prefix` tests along with those of `-common-suffix`.

Re: #262 

Moral question: Is it worth adding this function when users bent on bad practice like this can write the code themselves?

### CODE REVIEW

**Comment by Fuco1** [comment]
What do you mean by bad practice?

There's quite a lot of wrappers like this in dash where we do the "double reverse" trick.  I think it is convenient to have it both ways.

**Comment by basil-conto** [comment]
> What do you mean by bad practice?

By "bad" I mean inefficient and non-idiomatic. Because Elisp lists are singly linked, idiomatic programs are usually designed so as to avoid having to do this double reversal.

> There's quite a lot of wrappers like this in dash where we do the "double reverse" trick. I think it is convenient to have it both ways.

But I guess this is a library and it should provide such conveniences without complaining too much. :)

**Comment by Fuco1** [comment]
One of the really cool thing about having a lot of combinators is that it helps with prototyping.  I can do quite a lot with very little code when the library provides enough building blocks (and obviously I know dash quite well at this point :D).  So while not ready for production code this is quite nice to have when trying something out.

**Comment by basil-conto** [comment]
You're right, and I appreciate that. :)

By the way, I tried writing `-common-suffix` in terms of `--reduce-from` from scratch, rather than reusing `-common-prefix`, but this way is just as performant. Let me know if there's anything else you'd like me to iron out before merging this.

**Comment by basil-conto** [comment]
P.S. Any idea what's causing the (unrelated) Emacs 23 infloop in the tests?

**Comment by basil-conto** [comment]
Friendly ping.

**Comment by Fuco1** [comment]
Friendly pong!  I've assigned this to myself so it will show up in my planning, hopefully I'll get to it.

**Comment by basil-conto** [comment]
Ping, thanks. :)

**Comment by basil-conto** [comment]
I removed the doc changes created by `create-docs.sh` to avoid merge conflicts, so if and when this gets merged they should be regenerated.

Anything else holding this up?

**Pull request merged**
