### PR TITLE
Update CI configuration

### PR DESCRIPTION
**Pull request by basil-conto**
Remove Travis CI + Cask + EVM which are slow and problematic.

* `.github/workflows/test.yml`: Run CI also for PRs and with the latest Emacs release and Checkout Action versions.
* `.travis.yml`:
* `run-travis-ci.sh`: Remove files.

Re: #328.
Cc: @conao3

---

**Questions**:
1. Who gets notified when CI fails, and how?
2. Tests currently always succeed with Emacs Snapshot, even when there are failures. Can we realistically disallow failures with Emacs Snapshot, or will that be too noisy?

### CODE REVIEW

**Comment by conao3** [comment]
I don't know what I should comment on, but this change looks good to me.

**Comment by basil-conto** [comment]
> I don't know what I should comment on, but this change looks good to me.

That's all I needed to hear, thanks. :)

**Comment by Fuco1** [comment]
We should keep the cask file in case some people use the cask link feature.  I'm still sad that Elisp has no "package" definition file, and with cask falling out of favor we might actually go backwards when it comes to package development :/

**Review by Fuco1 — CHANGES_REQUESTED** [review]
let's keep the cask file

**Comment by basil-conto** [comment]
> We should keep the cask file

Sure, no problem.

> in case people use the cask link feature

What's that?

> I'm still sad that Elisp has no "package" definition file

What do you mean by that? How is it different to ELPA (the protocol's) `<foo>-pkg.el` files?

Any problems we have with Emacs packaging should be reported and discussed upstream, so that Emacs can improve for everyone.  Maybe it's my unfamiliarity with Cask talking, but I don't see why third-party solutions should be desirable here.

**Comment by Fuco1** [comment]
> What do you mean by that? How is it different to ELPA (the protocol's) <foo>-pkg.el files?

well of course you're right.  I just never used this directly and so I forgot it even existed.

Cask link is a feature for local development where you can link to a folder instead of a repository (remote or otherwise).  It requires that both the source and target packages have a cask file.

**Review by Fuco1 — APPROVED** [review]

**Comment by basil-conto** [comment]
> Cask link is a feature for local development where you can link to a folder instead of a repository (remote or otherwise). It requires that both the source and target packages have a cask file.

Looks like Cask linking also works with standard `-pkg.el` files; see https://cask.readthedocs.io/en/latest/guide/usage.html#cask-link. Does that address your concerns?

**Comment by basil-conto** [comment]
> > Cask link is a feature for local development where you can link to a folder instead of a repository (remote or otherwise). It requires that both the source and target packages have a cask file.
> 
> Looks like Cask linking also works with standard `-pkg.el` files; see https://cask.readthedocs.io/en/latest/guide/usage.html#cask-link. Does that address your concerns?

@Fuco1 Ping.

**Pull request merged**
